version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./pg/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:delegated
      - pg-data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: developer
      POSTGRES_DB: qadb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pg-data: